"""The array type for Slate."""

from __future__ import annotations

from slate_core.array._array import (
    Array,
    ArrayBuilder,
    ArrayConversion,
    NestedIndex,
    build,
)
from slate_core.array._conversion import (
    as_add_basis,
    as_diagonal_array,
    as_diagonal_basis,
    as_feature_basis,
    as_fundamental_basis,
    as_index_basis,
    as_linear_map_basis,
    as_mul_basis,
    as_outer_array,
    as_raw_array,
    as_sub_basis,
    as_transformed_basis,
    as_tuple_basis,
    cast_basis,
    flatten,
    nest,
)
from slate_core.array._misc import (
    abs,  # noqa: A004
    angle,
    arccos,
    arccosh,
    arcsin,
    arcsinh,
    arctan,
    arctanh,
    cast_as_dual,
    cos,
    cosh,
    dual_basis,
    exp,
    imag,
    is_tuple_basis_like,
    log,
    log2,
    log10,
    mod,
    real,
    sin,
    sinh,
    sqrt,
    square,
    supports_dtype,
    tan,
    tanh,
    unwrap,
)
from slate_core.array._stats import average, max, min, standard_deviation  # noqa: A004
from slate_core.array._transpose import conjugate, dagger, get_data_in_axes, transpose

__all__ = [
    "Array",
    "ArrayBuilder",
    "ArrayConversion",
    "NestedIndex",
    "abs",
    "angle",
    "arccos",
    "arccosh",
    "arcsin",
    "arcsinh",
    "arctan",
    "arctanh",
    "as_add_basis",
    "as_diagonal_array",
    "as_diagonal_basis",
    "as_feature_basis",
    "as_fundamental_basis",
    "as_index_basis",
    "as_linear_map_basis",
    "as_mul_basis",
    "as_outer_array",
    "as_raw_array",
    "as_sub_basis",
    "as_transformed_basis",
    "as_tuple_basis",
    "average",
    "build",
    "cast_as_dual",
    "cast_basis",
    "conjugate",
    "cos",
    "cosh",
    "dagger",
    "dual_basis",
    "exp",
    "flatten",
    "get_data_in_axes",
    "imag",
    "is_tuple_basis_like",
    "log",
    "log2",
    "log10",
    "max",
    "min",
    "mod",
    "nest",
    "real",
    "sin",
    "sinh",
    "sqrt",
    "square",
    "standard_deviation",
    "supports_dtype",
    "tan",
    "tanh",
    "transpose",
    "unwrap",
]
